"""The run plan and its cost, and the qsub lines that execute it.

    python -m ncpfold.plan                                   # whole study, 3 seeds
    python -m ncpfold.plan --eids E1 E4 E6 --seeds 1 --budget published
    python -m ncpfold.plan --eids E5 --seeds 1 --emit-qsub > submit_E5.sh

One SGE array job (10 tasks = 10 folds) per (variant, seed). The GPU-hour
figures use the per-encoder times measured in Phase 1 for the VAEs; the other
trainers carry estimates until their first fold is timed.
"""
from __future__ import annotations

import argparse
import shlex
from typing import List

from .catalogue import (HOURS_PER_ENCODER, STUDY_EIDS, encoders_of, hours_for,
                        study_runs)
from .folds import N_FOLDS


def plan_rows(eids: List[str], seeds: int, budget: str, n_folds: int = N_FOLDS):
    rows = []
    for sp in study_runs(eids):
        idx = [s.label for s in study_runs([sp.meta["eid"]])].index(sp.label)
        h = hours_for(sp, budget)
        rows.append({"eid": sp.meta["eid"], "run": idx, "label": sp.label, "kind": sp.kind,
                     "encoders": encoders_of(sp), "hours_per_fold": h,
                     "jobs": seeds, "tasks": seeds * n_folds, "gpu_hours": h * seeds * n_folds})
    return rows


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--eids", nargs="*", default=None)
    ap.add_argument("--seeds", type=int, default=3)
    ap.add_argument("--budget", default="chain", choices=["chain", "published"])
    ap.add_argument("--n-folds", type=int, default=N_FOLDS)
    ap.add_argument("--emit-qsub", action="store_true",
                    help="print qsub lines (one array job per variant and seed)")
    ap.add_argument("--data-dir", default="data/Full data")
    ap.add_argument("--out-root", default="outputs_perfold")
    ap.add_argument("--groups", default=None, help="group table for group-aware folds (qsub emission)")
    ap.add_argument("--group-mode", default="giles", choices=["giles", "strict"])
    args = ap.parse_args(argv)

    rows = plan_rows(args.eids or STUDY_EIDS, args.seeds, args.budget, args.n_folds)
    if args.emit_qsub:
        print("#!/bin/bash\n# generated by ncpfold.plan; one array job (folds) per variant x seed")
        for r in rows:
            for s in range(args.seeds):
                env = (f"EID={r['eid']},RUN={r['run']},SEED={s},BUDGET={args.budget},"
                       f"DATA_DIR={shlex.quote(args.data_dir)},OUT={shlex.quote(args.out_root)}")
                if args.groups:
                    env += f",GROUPS={shlex.quote(args.groups)},GROUP_MODE={args.group_mode}"
                print(f"qsub -t 1-{args.n_folds} -v {env} qsub/perfold_train.qsub.sh   # {r['label']}")
        return

    total_h = sum(r["gpu_hours"] for r in rows)
    total_tasks = sum(r["tasks"] for r in rows)
    print(f"{'eid':6s} {'run':>3s} {'label':40s} {'kind':12s} {'h/fold':>7s} {'tasks':>6s} {'GPU-h':>8s}")
    for r in rows:
        print(f"{r['eid']:6s} {r['run']:3d} {r['label']:40s} {r['kind']:12s} "
              f"{r['hours_per_fold']:7.2f} {r['tasks']:6d} {r['gpu_hours']:8.1f}")
    print(f"\n{len(rows)} variants x {args.seeds} seed(s) x {args.n_folds} folds = "
          f"{total_tasks} GPU tasks, ~{total_h:.0f} GPU-h ({args.budget} budget)")
    print("per-encoder hours assumed:", HOURS_PER_ENCODER)


if __name__ == "__main__":
    main()
